
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: production-k8s
  logs.region: ap-south-1
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"
