clusterName: production-k8s
region: us-east-1

cloudWatch:
  enabled: true
  logGroupName: /aws/containerinsights/production-k8s/application

serviceAccount:
  create: true

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 200Mi
