grafana:
  enabled: true
  adminPassword: admin123

  service:
    type: ClusterIP

  persistence:
    enabled: false

prometheus:
  enabled: true

  prometheusSpec:
    retention: 15d
    replicas: 1

    storageSpec: null

alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1

    storage: null

prometheusOperator:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

defaultRules:
  create: true
